mesh:
  build: .
  ports:
   - "80:80"
   - "9001:9001"
  restart: always
  working_dir: /app
  entrypoint: /app/start.sh
  user: root
  volumes:
   - ../:/app
  volumes_from:
    - gems
  links:
   - redis
   - mongo
redis:
  image: zarkzork/redis
mongo:
  image: mongo
gems:
  image: zarkzork/gems
